### ISSUE TITLE
Theme on navbar

### ISSUE THREAD

**Issue by Wasehdev** [quran/quran.com-frontend-next#1053]
We need an option to change the theme on the navbar so user can change the theme right away after coming to the website if he/she feels uncomfortable with current theme

![image](https://user-images.githubusercontent.com/54233738/147848505-1a7804e0-b588-4a12-ae97-ce0b72972d2a.png)

**Comment by abdulhamidOumer** [comment]
Hey @Wasehdev , I can take care of this. I was thinking the same kind of selector as the locale but with a dynamic icon for the button based on the selected theme. WDYT?

**Comment by abdulhamidOumer** [comment]
> Hey @Wasehdev , I can take care of this. I was thinking the same kind of selector as the locale but with a dynamic icon for the button based on the selected theme. WDYT?

@muhajirdev  @osamasayed what do you guys think?
