### ISSUE TITLE
add "next" and "prev" new tafsir view

### ISSUE THREAD

**Issue by tifa2UP** [quran/quran.com-frontend-next#1054]

**Comment by faiqali1** [comment]
اَلسَّلَامُ عَلَيْكُمْ

I'm not quite sure if I follow?
Mind sharing a screenshot of what you mean?

From what I can see, there does appear to be a next and previous button in 
![image](https://user-images.githubusercontent.com/74228240/204121269-f5325a0d-3122-4218-9498-b9d8157ead0f.png)

**Comment by hazem3500** [comment]
The **Prev** and **Next** Ayah buttons are in the Tafsir view, as @faiqali1 mentioned, so unless you were referring to another tafsir view, shouldn't we close this issue? 👀

**Comment by osamasayed** [comment]
> The **Prev** and **Next** Ayah buttons are in the Tafsir view, as @faiqali1 mentioned, so unless you were referring to another tafsir view, shouldn't we close this issue? 👀

Yup, thanks for the reminder :) A lot of the issues on Github are pretty out-dated :).
