### ISSUE TITLE
"Advanced Copy" Lost modal box  & Copy problems. Someone must be work and test "Advanced copy".. please

### ISSUE THREAD

**Issue by selim** [quran/quran.com-frontend-next#1061]
Please someone work on advanced copy there is so  many bugs..

When select Advanced copy from ayaat menu, modal box open; move the cursor, modal box closing or hiding?... ass seen on video attached.

Web      : https://beta.quran.com
Browser: FireFox dev edition

https://user-images.githubusercontent.com/241385/147901480-0a5f696c-eecc-46ec-a433-402940421d86.mov

8<--- update
if i squeeze window, and click rigth button from keyboard i can edit ayat range and copy.. but copied all of my reading session, does not copy ayat range. 

<img width="518" alt="image" src="https://user-images.githubusercontent.com/241385/148007941-3a3f79d6-2c25-440a-bc89-ac8b5d778e8d.png">

**Comment by 9inpachi** [comment]
Taking this. Might take some time though.

**Comment by 9inpachi** [comment]
Salam,

So I had a go at this last week but couldn't fix it. This doesn't only happen with Advanced Copy. It also happens in the Tafsirs dialog. I will list down the things I found.

1. Because of `onClickOutside` -> `onInteractionOutside` of modal.
    Passed from `src/components/dls/Modal/Content.tsx`, the `onInteractionOutside` is called on mouse move in Firefox. This might be related to the `@radix-ui/react-dialog` library being used or somewhere upper in the rendering of components. I couldn't find the exact reason because the code is quite distributed.
    I added a new Modal story to check if it happens in an isolated environment, but it doesn't. The `onInteractionOutside` works as expected and isn't called on mouse move.
    **Components Involved:**
      * `src/components/dls/Modal/Content.tsx`
      * `src/components/dls/Modal/Modal.tsx`
      * `src/components/dls/Modal/Content`
2. Because of modal content.
    Even after removing `onInteractionOutside`, the modal was still closing on mouse move. This is exactly what happens with the Tafsirs dialog as well. Once I remove the children of the `Modal` component being used, it works fine. I am not sure how everything is related.
    **Components Involved:**
      * `src/components/Verse/VerseActionAdvancedCopy.tsx`
      * `src/components/QuranReader/TafsirView/TafsirVerseAction.tsx`
      * `src/components/dls/ContentModal/ContentModal.tsx`

I will most probably won't go into it any deeper unfortunately. So if anyone else wants to work on it, I hope the pointers here help.

JazakAllah.

**Comment by yj7o5** [comment]
I'm taking a look
