### ISSUE TITLE
Pass Tajweed Mushaf id to Tafsirs API

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-next#1066]
When a user selected Tajeweed Mushaf then opens the Tafsirs Modal, it shows broken images like the one below:

<img width="867" alt="Screen Shot 2022-01-04 at 10 19 22" src="https://user-images.githubusercontent.com/15169499/148005215-feb700af-5393-4050-9d53-fc16e40408f2.png">

**Comment by nabeeltahirdeveloper** [comment]
In this page we need to show normal Ayah or Ayah in tajweed font?

**Comment by nabeeltahirdeveloper** [comment]
@naveed-ahmad ??

**Comment by naveed-ahmad** [comment]
@nabeeltahirdeveloper we want to show Mushaf user has selected from the settings. If Tajweed Mushaf is selected, we should show tajweed.
