### ISSUE TITLE
Feature: share link with language  of translation

### ISSUE THREAD

**Issue by muhammadsiddiqbe** [quran/quran.com-frontend-next#1085]
Assalamu alaikum brothers. If you add an option to send surah link with choosing a translation it would be mashaAllah)
Like this one
`https://quran.com/2/155?translation=uzbek-crylic`

**Comment by shakib2018** [comment]
I think it's already planned https://feedback.quran.com/b/bugs/about-storing-configured-values/

**Comment by mnmami** [comment]
+1'ing this.

@shakib2018 could you point me to where this could be implemented and I try to code it and file a PR for it?

بارك الله في جهودكم

**Comment by shakib2018** [comment]
@mnmami  I think they already have it. See https://beta.quran.com/8/3?translations=131%2C84

**Comment by mnmami** [comment]
Great, ma sha Allah! I had already hovered over that button couple of times but didn't get the extra argument in the query string. Clicking showed them. Thanks @shakib2018 and the developers for making this possible.

**Comment by osamasayed** [comment]
Jazakum Allah Khairan everyone!
