### ISSUE TITLE
create global nav

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend-next#11]
design:
![image](https://user-images.githubusercontent.com/3749095/81525575-290bd080-9323-11ea-9107-81aa9e9dec90.png)
![image](https://user-images.githubusercontent.com/3749095/81525588-32953880-9323-11ea-896c-5d24f0705152.png)

**Comment by mmahalwy** [comment]
please use https://react-icons.netlify.com/#/ for icons 🙏

**Comment by soghammed** [comment]
Is the Download button necessary

**Comment by soghammed** [comment]
any idea how to get the media query working? I've added the navbar and tested the code for mob design, but cant get the media query work on resize
