### ISSUE TITLE
Surah At-Takhathur last ayar repeated in translation view

### ISSUE THREAD

**Issue by AadilMehrajBhat** [quran/quran.com-frontend-next#1113]
The last ayah of surah takhathur is repeated when view in translation view:
https://next.quran.com/103
![Screenshot 2022-01-18 at 10 46 26 AM](https://user-images.githubusercontent.com/26774310/149875421-ec24793c-c6ed-492b-9c37-3d9713245425.png)

**Comment by osamasayed** [comment]
Alsalamu Alikum @AadilMehrajBhat, I believe this issue has been resolved already. https://quran.com/102 Jazak Allah Khairan!
