### ISSUE TITLE
`PopoverMenu` & `Modal` not working in Storybook

### ISSUE THREAD

**Issue by ahmedriad1** [quran/quran.com-frontend-next#1151]
Currently `PopoverMenu` & `Modal` components are not working in Storybook, as well as their code preview 

Popover Menu:

![popover-menu](https://user-images.githubusercontent.com/58295120/151393247-470da852-4831-4593-b66c-9a822e2efe01.gif)

Modal:

![modal](https://user-images.githubusercontent.com/58295120/151393302-b1aca931-31d1-415f-bc5f-725a76b8c675.gif)

**Comment by osamasayed** [comment]
Alsalamu Alikum @ahmedriad1, is this something you would like to help with?

**Comment by ahmedriad1** [comment]
Wa Alaykum Aslam @osamasayed, sure I'll fix it now 😄
