### ISSUE TITLE
add verse controls

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend-next#12]
design: 
![image](https://user-images.githubusercontent.com/3749095/81525681-7a1bc480-9323-11ea-8499-1767a7d09a04.png)
https://invis.io/RUPU8EFKCPJ#/275891921_Desktop-100-Surah-R01
https://invis.io/5FPOLZNABG3#/337633725_Mobile_100_Surah_-_3_More_Menu

**Comment by sourov009** [comment]
Salam, anyone started to work on this? If anyone has, which issue can I take up to start contributing?
