### ISSUE TITLE
[feature]: Keyboard shortcut for searching and jumping to a specific surah (by name) and verse

### ISSUE THREAD

**Issue by swawif** [quran/quran.com-frontend-next#1230]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

Assalammualaikum

I would like to suggest a feature that i think would be useful to many people that do a lot of referencing from quran.com

I usually have an ayah that i want to reference from quran. I know the verse number, but not the surah number

usually what i do is, i search the surah name in the sidebar, find out the surah number, then write the URL manually.

i find this faster as it require less movement to the mouse.

It would be awesome if there is a way for us to do this faster

### Your purposed solution for this feature

maybe you could improve on the `ctrl+k` navigation by doing

1. user types incomplete surah name
2. suggest matching surah name
3. user press tab to autocomplete surah name
4. user add ' : + verse number' then press enter
5. returns the specific surah and verse

so, if user would like to go to An-nisa, verse 101, they would just type `ctrl+k` -> `'an-nisa : 101'`

Jazakallahu khairan, wa barakallahu fikum

**Comment by hazem3500** [comment]
Doesn't it already somewhat do what you're suggesting? 🤔

![image](https://user-images.githubusercontent.com/22430645/220407452-fddc952c-8c5d-4d07-bdf1-fac4560931a6.png)

**Comment by osamasayed** [comment]
Yup it does that already. JazakAllah Khairan.
