### ISSUE TITLE
Problem using Tarteel voice search.

### ISSUE THREAD

**Issue by microart-inc** [quran/quran.com-frontend-next#1235]
Tried on windows and android, voice search fails with an error.

Message: "An error has occurred, please try again later. Or download the Tarteel app"

**Comment by yj7o5** [comment]
I'll take a look

**Comment by yj7o5** [comment]
Issue is with the prod deployment process not have the `NEXT_PUBLIC_TARTEEL_VS_API_KEY` set, thus the call to the tarteel api for voice fails: 
<img width="547" alt="image" src="https://user-images.githubusercontent.com/7938533/153967485-875612ae-cac4-4cf2-91e7-0d93e8482e3e.png">

**Comment by osamasayed** [comment]
Alsalamu Alikum, I believe this issue no longer happens, if it does, please re-open this issue, thank you!
