### ISSUE TITLE
What happened to rails app ?

### ISSUE THREAD

**Issue by allyraza** [quran/quran.com-frontend-next#14]
Salam, I have been following the project for some time, I have no excuse to not to contribute sorry about that.

When i first came across this project it was a react app then the efforts were shifted to rails app, I see now there is `next.js` app.

Would it not be reasonable to focus on one implementation and consolidate everything.

Jazakallah for you effort

**Comment by mmahalwy** [comment]
Focus on this. We will deprecate the rails app eventually. This will be the future
