### ISSUE TITLE
Arabic chapter names showing outside borders on hover

### ISSUE THREAD

**Issue by mistat44** [quran/quran.com-frontend-next#15]
Some of the chapter names in Arabic are showing outside the border when hovering over them. I hope the image below demonstrates the minor issue. I can help and raise a PR if its not been noted before.

![Arabic Chapter name Outside borders](https://user-images.githubusercontent.com/32406853/81942038-30d1ba80-962c-11ea-90a1-6556eb3893a7.png)

**Comment by mmahalwy** [comment]
@mistat44 please do!

**Comment by mistat44** [comment]
sorry I just realized this bug exists in the previous build and not this repo :(
