### ISSUE TITLE
[bug]: google search result link is off

### ISSUE THREAD

**Issue by marafa-sugarcrm** [quran/quran.com-frontend-next#1526]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

i was searching google for the keywords `quran 49:11`

issues
- i was expecting quran.com to be the first result
- i see legacy.quran.com is the first result
- the results have the right title
- the link goes to 49:1 . it does not go straight to the expected verse that i am searching for

![Screen Shot 2022-03-28 at 9 39 35 AM](https://user-images.githubusercontent.com/69474017/160410299-bc0f67bb-3ef2-4c92-84ce-1be09306605a.png)
 

### Steps to reproduce

1. click https://www.google.com/search?q=quran+49%3A11&rlz=1C5GCEM_enUS950US950&oq=quran+49%3A11&aqs=chrome..69i57j0i512l3j69i60l4.4034j0j7&sourceid=chrome&ie=UTF-8
2. select the quran.com link for the verse

### Environment (please complete the following information) and Add any other context about this bug

mac osx - latest
chrome - latest

### Environment

Production(quran.com)

**Comment by hazem3500** [comment]
I've tested it, and the links open at `49:11` 🤔 

Though the legacy.quran.com shouldn't really be index first 😅

**Comment by 3rg1s** [comment]
Hello there, this issue seems to not be reproducible anymore. quran.com is the first page shown in the google search. Can we close this issue?

**Comment by marafa-sugarcrm** [comment]
reproduction
![Screenshot 2024-03-20 at 8 15 32 AM](https://github.com/quran/quran.com-frontend-next/assets/69474017/0c570af4-42ba-4c60-a0f0-b8ecf9e66417)

**Comment by 3rg1s** [comment]
> reproduction
> 
> ![Screenshot 2024-03-20 at 8 15 32 AM](https://github.com/quran/quran.com-frontend-next/assets/69474017/0c570af4-42ba-4c60-a0f0-b8ecf9e66417)
> 
> 

Seems like this is not the case for everyone then
