### ISSUE TITLE
[bug]: when sharing a translated verse on facebook, the arabic text is used

### ISSUE THREAD

**Issue by marafa-sugarcrm** [quran/quran.com-frontend-next#1527]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

when sharing a link like https://quran.com/49/11?translations=22

it is expected that the translation is given priority over the arabic. instead it is the arabic that is seen in the preview of the link

### Steps to reproduce

share a translation link

### Environment (please complete the following information) and Add any other context about this bug

facebook.com

### Environment

Staging(next.quran.com)

**Comment by hazem3500** [comment]
Could you elaborate on your point? 🤔
I've tested the link on Facebook and it looks like this 👇 
Is it supposed to look differently?

![image](https://user-images.githubusercontent.com/22430645/220404938-e9bfc9c1-dbd4-4461-8993-580f71ba85c5.png)
