### ISSUE TITLE
[question]: Can someone from the devs team tell me which font is King Fahad Complex V1 and V2 respectively?

### ISSUE THREAD

**Issue by S0FTiFiED** [quran/quran.com-frontend-next#1531]
### Summary

Apologies, don't know where to ask this so I am opening a new issue.

Just as I asked in the title I am wanting to know which font has been used as King Fahad Complex V1 and V2. Are they the Naskh or the Hafs? I know little to nothing about Arabic fonts.

I tried to copy the text in an editor but it shows these weird glyphs which I am not sure where they are coming from.

![weird glyphs](https://user-images.githubusercontent.com/87467628/160473790-3016ba0d-b215-46b2-9e98-ca34c05c2810.png)

And could someone link to the download page of the font if possible?

**Comment by naveed-ahmad** [comment]
V1 and v2 are Hafs fonts and available in this repo. See public/fonts directory
