### ISSUE TITLE
[bug]: Issue with word wrapping in Surah At-Tawbah

### ISSUE THREAD

**Issue by alsharmani1** [quran/quran.com-frontend-next#1581]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

The issue exists in Surah At-Tawbah, first word of Ayah 19
The word wrapped as shown in the screenshot below
![image](https://user-images.githubusercontent.com/31460547/162852479-bd99e864-9848-4781-b9bf-758e6d6a34c4.png)

The only fix I could think of it changing the font size to 35px  as shown below
![image](https://user-images.githubusercontent.com/31460547/162852653-0a8bf7bf-33e0-4c93-b7b9-0d9b84384e21.png)

### Steps to reproduce

- Go to Quran.com
- Open Surah At-Tawbah
- Go to Verse 19
- First word there is wrapped

### Environment (please complete the following information) and Add any other context about this bug

OS: Windows
Browser: Chrome
Version: 100.0.4896.75 (Official Build) (64-bit)

### Environment

Production(quran.com)

**Comment by mo-othman** [comment]
@alsharmani1 I think nowrap white space would be the suitable approach I have created the PR for that

**Comment by alsharmani1** [comment]
Perfect, thank you!
