### ISSUE TITLE
[bug]: "Next Surah" and "Previous Surah" buttons sometimes link to the wrong surahs

### ISSUE THREAD

**Issue by kritixilithos** [quran/quran.com-frontend-next#1606]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Assalamu alaykum,

Sometimes the "Next Surah" and "Previous Surah" buttons behave as if the surah number was one less than it actually is. I've listed a minimal repro below.

### Relevant log output

```shell
Source map error: Error: request failed with status 404
Resource URL: https://next.quran.com/15
Source Map URL: 10842d967ad746bf.css.map
```

### Steps to reproduce

1. Go to https://next.quran.com/14
2. Then scroll all the way down and click on "Next surah"
3. Now in surah 15, scroll all the way down and click on "Next surah"

Expected: "Next surah" should bring me to https://next.quran.com/16
Actual: "Next surah" brought me to https://next.quran.com/15

### Environment (please complete the following information) and Add any other context about this bug

OS: Windows 10
Browser: Firefox 99.0.1

### Environment

Staging(next.quran.com)

**Comment by Shameel123** [comment]
Agreed.
Further details:

Previous:
![image](https://user-images.githubusercontent.com/45264147/164790593-594bcdb2-357c-4be3-82a6-26797932d0eb.png)

Next:
![image](https://user-images.githubusercontent.com/45264147/164790714-13dad01d-f9ee-4dc2-85fc-8bb1912f38c7.png)


I believe, the possible reason is that, after rendering the page, the links of these two buttons are not being updated.

**Comment by Shameel123** [comment]
Path:
`Components -> QuranReader -> EndOfScrollingSocntrols -> index.ts -> ChapterControls `
The issue is in lastVerse which is being returned from parent in `EndOfScrollingControls` file.
I am trying to resolve it.

**Comment by Admia1** [comment]
Assalamo alaykom.
I tried to log some variables in different files and found what caused this problem.
The following variable stores all verses of the chapter which is being read.
` Components -> QuranReader -> TranslationView -> index.ts -> verse `
But when you press `next Sureh` button the list of verses won't get flushed but whenever you go to a certain verse in front-end it update that part of list.

**Comment by osamasayed** [comment]
This issue has been resolved. JazakAllah Kahiran for reporting.
