### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by thecashewtrader** [quran/quran.com-frontend-next#161]
Sorry if this is the wrong place to post this.

I am making a similar site but minimalist (pure html, no react) at https://thecashewtrader.gitlab.io/simple-quran
Currently it uses King Fahad Quran Complex V1 Fonts
I would like to switch to V2, but the text for V2 doesn't seem to be available in their repo https://github.com/alquran-foundation/qpc-fonts/

Could yall tell me where u got the text for the V2 font.

**Comment by naveed-ahmad** [comment]
You can fetch v2 codes via our api https://api.quran.com/api/v4/quran/verses/code_v2

**Comment by thecashewtrader** [comment]
جزاك اللهُ خير
