### ISSUE TITLE
[bug]: Getting play undefined instead on Popup in production site

### ISSUE THREAD

**Issue by ashadnasim52** [quran/quran.com-frontend-next#1618]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When some surah is playing and then I play next then get the popup of 

**Click on "Start Over" if you would like to play undefined instead**

The issue is getting play undefined,  expected output was to show the surah name

<img width="725" alt="image" src="https://user-images.githubusercontent.com/38835999/165920615-6123be6c-a1c6-46f5-9abc-710909f045ca.png">

### Relevant log output

```shell
no logs
```

### Steps to reproduce

1. Play any surah
2. select on any other
3. will get the pupup

### Environment (please complete the following information) and Add any other context about this bug

Mac OS
Chrome

### Environment

Production(quran.com)

**Comment by ashadnasim52** [comment]
I had some experience in Nextjs and Nodejs, if anyway I can contribute then please let me know

**Comment by osamasayed** [comment]
Jazak Allah Khairan for reporting this. It has already been fixed Alhamdulelah.
