### ISSUE TITLE
[bug]: Incomplete translation

### ISSUE THREAD

**Issue by itsazzad** [quran/quran.com-frontend-next#1622]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

https://quran.com/64/14?translations=213 The translation is incomplete.

### Relevant log output

```shell
https://quran.com/64/14?translations=213 The translation is incomplete.
```

### Steps to reproduce

https://quran.com/64/14?translations=213 The translation is incomplete.

### Environment (please complete the following information) and Add any other context about this bug

Browser: Chrome

### Environment

Production(quran.com)

**Comment by hazem3500** [comment]
I'm guessing this issue no longer exists? 🤔

I'm going to the link, and it seems that it's loading properly, and I'm not seeing this error 👇 in the console.
```
https://quran.com/64/14?translations=213 The translation is incomplete.
```

![image](https://user-images.githubusercontent.com/22430645/220400971-d78ca06a-05db-4e68-8ca5-a9325ae426cd.png)

**Comment by osamasayed** [comment]
Salam @itsazzad, Jazak Allah Khairan for reporting, we cannot reproduce the issue. Will close and feel free to re-report if it still persists.

**Comment by itsazzad** [comment]
@hazem3500 @osamasayed 
The highlighted part of the English translation is missing in the Bengali translation.
![image](https://user-images.githubusercontent.com/54909/220635664-fe5ec1f5-e60c-4166-9ff3-f8172857d6f1.png)

**Comment by osamasayed** [comment]
> @hazem3500 @osamasayed 
> 
> The highlighted part of the English translation is missing in the Bengali translation.
> 
> ![image](https://user-images.githubusercontent.com/54909/220635664-fe5ec1f5-e60c-4166-9ff3-f8172857d6f1.png)
> 
> 

Ah so you mean it's a content issue and not a functionality issue right? If so, please submit the issue to https://feedback.quran.com/translation-and-tafsir-errors
