### ISSUE TITLE
[question]: Is there any e2e test for front-end or list of urls ?

### ISSUE THREAD

**Issue by Admia1** [quran/quran.com-frontend-next#1631]
### Summary

Assalamo Alayakom
I was working on Bug #1606 which led to pull request #1620 which i managed to fix it.
The problem had happened as next chapter button was using data from verses not the request user had made. I managed to fix it for chapter reading scenario but for reading hizb and juz and so on, i need to add more types. when i was tracing the code i found that in some scenarios instead of storing data in classes they are stored in string which make it impossible to trace code without reading whole of it.

I'm asking if there is some test available within this project or a list of URLS which should work so i can check develop easier and more confident.

**Comment by osamasayed** [comment]
Alsalamu Alikum, @Admia1 we don't have e2e tests setup as of yet but we already have the infra for it using [playwright](https://playwright.dev/). Let me know if you want to help with setting up e2e tests. My discord is Osama Sayed#0504, JazakAllah Khairan.
