### ISSUE TITLE
[feature]: Extend repeat ranges for audio repeat settings

### ISSUE THREAD

**Issue by snnsnn** [quran/quran.com-frontend-next#1647]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

Current implementation moves from 3 to loop, can you push the upper boundary to 5 or 10.

### Your purposed solution for this feature

Change the upper range to a higher value like 10.

**Comment by sabakhilji** [comment]
Assalamualaikum I want to understand this issue clearly and also want to take this issue. Is this issue still open?

**Comment by snnsnn** [comment]
The play range for the audio player goes from 3 straight to infinity which may not be desirable if you want to listen each surah or ayah say 5 times. Pushing the upper boundary to 10 may be more practical. 

![image](https://user-images.githubusercontent.com/16473630/198727118-a8bb08dc-bb07-416d-8bb5-d5b10546f256.png)

A better alternative could be accepting custom number through an input field. The number displaying the repetition (i highlighted it) can turn into an input field when clicked, through  which user can set the desired number of repetition. This way, you can keep the current implementation while providing a more flexible alternative.

![image](https://user-images.githubusercontent.com/16473630/198729259-23f5fd74-000c-48a7-b9fc-504352f73a5f.png)

**Comment by sabakhilji** [comment]
Assalamualaikum @osamasayed please correct me if I am wrong. Can this task be done just by changing the RepeatSetting props max value to a number instead of infinity? I am a new developer and trying to figure it out please help!

**Comment by osamasayed** [comment]
> Assalamualaikum @osamasayed please correct me if I am wrong. Can this task be done just by changing the RepeatSetting props max value to a number instead of infinity? I am a new developer and trying to figure it out please help!

We have `infinityThreshold` inside `src/components/AudioPlayer/RepeatAudioModal/RepeatAudioModal.tsx` that simply needs to be increased from `3` to a higher value maybe to `7` after which infinity will be selected. Feel free to open a PR with this change and I will take a look inshaAllah.
