### ISSUE TITLE
Selecting Translations don't work (Not adding new ones, not removing current ones)

### ISSUE THREAD

**Issue by farwest912** [quran/quran.com-frontend-next#168]
As Salamu Alaikum, 

Even "Feedback" function did not submit my message, I decided to find you on Github and write you here. 

The ability to switch to different translations is no longer working (since you renewed the User Interface) that we access through "Settings" on Upper Bar section, but only the two pre-selected translators (Mustafa Khattab and Saheeh International) are shown. 

I am using quran.com for a long time, this problem is continuing since you renewed the User Interface, and now I miss the usability of the old version already. I checked this on Opera and Mozilla browsers (latest versions), it doesn't work in none of them (and in old version of Edge, setting button doesn't work at all too). 

InshaAllah you can fix the function of switching the translators like we were able to do it before the update in User Interface, thanks. JazakAllah for this beautiful website which I suggest to everyone possible.

**Comment by validity-check** [comment]
Be more specific. What features aren't working?

**Comment by farwest912** [comment]
Then see the screenshot. I thought I was very specific enough, hope you can find this clearer to understand. 
![Selection doesn't reflect](https://user-images.githubusercontent.com/68647386/119888978-b32ed300-bf3e-11eb-9bb4-f68807047bf3.jpg)

**Comment by farwest912** [comment]
Then, your Feedback button. See the image again. 

![Submitting Feedback](https://user-images.githubusercontent.com/68647386/119889438-36502900-bf3f-11eb-8462-7ce3b26903f1.jpg)

**Comment by farwest912** [comment]
Hope the pictures made the case clearer for you now. 

What is most important is, fixing the selecting Translations, currently selections (any selection on Translation list, any language) don't reflect to the reading page at all.

**Comment by benomaire** [comment]
related: 
https://github.com/quran/quran.com-api/issues/356
https://github.com/quran/quran.com-api/issues/330

**Comment by farwest912** [comment]
@benomaire  I am on PC, not Mobile. 
In this case, I cannot add new translations + cannot remove current translations. In summary, "selecting" function doesn't work.

**Comment by benomaire** [comment]
@farwest912 This should be fixed. Check: https://github.com/quran/quran.com-frontend-v2/issues/443
You can also try the new website: https://next.quran.com/  and write your feedback

**Comment by farwest912** [comment]
Thanks for the changes. Currently quran.com is working without issues in
the last weeks for the problem I had reported. Right now, I am able to
change translators without problem, so I declare that the problem I had
posted is "SOLVED".

Also, I tried https://next.quran.com as you suggested and adding additional
translators is difficult in this one. Namely:
-It requires a new user to "figure out" clicking to Search/Zoom icon and I
fear many wouldn't notice that function. (Clicking that icon opens an
additional sub panel to browse other available translations.)
-Available translations look like mixed, some Urdu translations are between
English, some English ones are very down below other languages too.
-The subpanel (available translations) Panel is vertically very narrow,
also mixing with behind text easily due to having same background color
(sub panel should have a different color, a different color shade would be
okay too). Currently it is not comfortable to view all available
translations under the interested language, I prefer the current quran.com
version.
-In summary, I would prefer the current quran.com version over this one in
usability and eye-candy look for those who work on quran.com for
translation comparison purposes at the moment.

Feedback & Suggestions for Current Version:
-Translations should be listed A-Z Languages, If I am looking for German I
shouldn't find it below Uzbek.
-If you can work on Cookie and if the page remembers which languages or
translations were chosen last, that would be convenience.
-Current translations are very limited. For example I found Yaşar Nuri
Öztürk's translation in Turkish as best and not finding it in available
list is sad for me. You can find all Turkish translations here (and it
follows similar link pattern like yours, sure=1, ayet=1, or sure=2,
ayet=255 for Ayat al Kursi):
https://kuranmeali.com/AyetKarsilastirma.php?sure=1&ayet=1

Wishing you all the best and easiness in your works.

benomaire ***@***.***>, 9 Eyl 2021 Per, 23:38 tarihinde şunu
yazdı:
