### ISSUE TITLE
write tests for storybook components

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend-next#17]
- setup jest test integration with storybook
- setup jest for testing all components

**Comment by hazem3500** [comment]
#18

**Comment by murtuzasyed** [comment]
Assigning this to myself.

**Comment by murtuzasyed** [comment]
Is this still open or closed in https://github.com/quran/quran.com-frontend-next/pull/18

**Comment by mmahalwy** [comment]
@murtuzasyed this is closed.
