### ISSUE TITLE
[bug]: In tajweed mode there is no sign of sajad, but it does have this sign(mark) of sajda in other modes such as Uthmani

### ISSUE THREAD

**Issue by feruz111** [quran/quran.com-frontend-next#1739]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When i am in Tajweed mode there is no sign (mark) of sajda, but if i am in Uthmani mode we do have this sign. This is the case for every sajda ayat in quran
<img width="938" alt="Screenshot 2022-08-07 at 17 56 02" src="https://user-images.githubusercontent.com/63453253/183302240-2d807edd-3820-412f-9268-61d949caef74.png">
<img width="811" alt="Screenshot 2022-08-07 at 18 02 37" src="https://user-images.githubusercontent.com/63453253/183302496-36fec2b0-dcfd-42f4-9b93-d992a9b0353c.png">

### Steps to reproduce

1. go to tajweed mode
2. go to surah al-alaq
3. go to end of surah and you will not see sign (mark) of sajda
4. This is the case for every sajda ayat in quran

### Environment (please complete the following information) and Add any other context about this bug

OS: the problem is with OS

### Environment

Production(quran.com)

**Comment by osamasayed** [comment]
Salamu Alikum @feruz111, the screenshot you have shared already shows that there is a Sajdah sign for Tajweed mode. Closing the issue. Feel free to comment and I will open it again if necessary.

<img width="242" alt="Screen Shot 2022-10-24 at 4 32 47 PM" src="https://user-images.githubusercontent.com/15169499/197551628-d23cc648-0ff5-4ece-a83e-b8a410ddedff.png">

**Comment by feruz111** [comment]
@osamasayed Could you pls send the screenshot and show where is the sajdah sign in tajweed mode I was not able to find it
