### ISSUE TITLE
[feature]: Choose a narration or readings (Warsh & Hafs)

### ISSUE THREAD

**Issue by omarouhra** [quran/quran.com-frontend-next#1746]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

Asalamo alyukum, First Thank you so much for this amazing app! just go a small feature suggestion! that will be amazing if I can choose a reading such as "Warsh"!

### Your purposed solution for this feature

the same thing goes for the reciters! Thank you 👍

**Comment by osamasayed** [comment]
JazakAllah Khairan for your suggestion. InshAllah we are planning to add more Qira'at to Quran.com.
