### ISSUE TITLE
[bug]: Overflowing reciters menu

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-next#1747]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When I try to change the reciter from the audio player's body while playing a Surah/Ayah, the reciter's menu overflows out of the boundaries of the screen.

![294503139_585308603088299_1162405873900325791_n](https://user-images.githubusercontent.com/15169499/185745801-cfbf1b51-9c36-4850-baf0-27c221352681.jpeg)

### Steps to reproduce

1. Go to Surah Al Fatihah https://quran.com/1
2. Click "Play Audio" button on top of the page
3. Audio player's body should show
4. Click on "..." (More) button.
5. Click "Select Reciter" menu item.

### Environment (please complete the following information) and Add any other context about this bug

OS: iPhone X 15.6
Browser: Firefox
Version: Daylight 103.1 (15076)

### Environment

Production(quran.com)

**Comment by Anas-debug** [comment]
I would like to take this issue.

**Comment by osamasayed** [comment]
> I would like to take this issue.

Sure that would be great. Thank you!

**Comment by farajist** [comment]
Still on it @Anas-debug ? 
Do you think it should be loooking like this @osamasayed ? 
![image](https://user-images.githubusercontent.com/28780579/186724938-4101870d-10f3-4042-857e-abdbe423a05a.png)

**Comment by osamasayed** [comment]
> Still on it @Anas-debug ? Do you think it should be loooking like this @osamasayed ? ![image](https://user-images.githubusercontent.com/28780579/186724938-4101870d-10f3-4042-857e-abdbe423a05a.png)
> 
> PS: I reproduced the issue using chrome devtools and it seems to happen in multiple mobile devices

Yes I think this is looking great, on very small devices, one solution I have in mind is that we should be splitting long text into multiple lines if it's overflowing.

**Comment by farajist** [comment]
I noticed that the whole container overflows mainly due to `.overriddenPopoverMenuContentPositioning` having an `absolute` position, setting to `fixed` on `smallerThanTablet` solved the overflow issue, do you think it's enough :thinking: ?

**Comment by osamasayed** [comment]
> I noticed that the whole container overflows mainly due to `.overriddenPopoverMenuContentPositioning` having an `absolute` position, setting to `fixed` on `smallerThanTablet` solved the overflow issue, do you think it's enough @osamasayed 🤔 ?

@Anas-debug are you still on it? If not, @farajist would be great if you push a PR to fix it and I will take a look inshAllah. Jazak Allah Khairan!
