### ISSUE TITLE
[bug]: Application Error Disclosure

### ISSUE THREAD

**Issue by thehassantahir** [quran/quran.com-frontend-next#1755]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

> https://next.quran.com/_next/static/chunks/main-f4e46be024ad22ae.js 

### Issue
This page contains an error/warning message that may disclose sensitive information like the location of the file that produced the unhandled exception. This information can be used to launch further attacks against the web application

### Solution 
Implement custom error pages.

### Evidence
Internal Server Error

### Steps to reproduce

1. See https://next.quran.com/_next/static/chunks/main-f4e46be024ad22ae.js

### Environment (please complete the following information) and Add any other context about this bug

OS: Kali Linux
Browser: Google Chrome
Version: 104.0.5112.101

### Environment

Staging(next.quran.com)

**Comment by osamasayed** [comment]
Salamu Alikum @thehassantahir can you elaborate more on how does including a warning message inside the JS bundle can lead to security threat?
