### ISSUE TITLE
Add route for Hizb

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-next#1760]
Currently Quran.com supports routes for:

- a Surah e.g. https://quran.com/al-kahf
- A verse e.g. https://quran.com/al-kahf/1
- A juz e.g. https://quran.com/juz/1
- A page e.g. https://quran.com/page/1

We should also support for reading a specific hizb as well. The route should be like `/hizb/{hizbNumber}`. Quran.com already has an [API](https://quran.api-docs.io/v4/verses/by-hizb-number) that gets the verses of a specific hizb.

**Comment by ahmedriad1** [comment]
Working on this now
