### ISSUE TITLE
Add route for Rub'

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-next#1761]
Currently Quran.com supports routes for:

- a Surah e.g. https://quran.com/al-kahf
- A verse e.g. https://quran.com/al-kahf/1
- A juz e.g. https://quran.com/juz/1
- A page e.g. https://quran.com/page/1

We should also support for reading a specific Rub' as well. The route should be like `/rub/{rubNumber}`. Quran.com already has an [API](https://quran.api-docs.io/v4/verses/by-rub-number) that gets the verses of a specific Rub'.

**Comment by talal-najam** [comment]
Happy to give this a try.

**Comment by osamasayed** [comment]
> 

Would be great! Let me know if you have any questions.

**Comment by osamasayed** [comment]
> Happy to give this a try.
Would be great! Let me know if you have any questions.

**Comment by osamasayed** [comment]
> Happy to give this a try.

Would be great! Let me know if you have any questions.
