### ISSUE TITLE
[feature]: Bookmark groups / topics OR labels

### ISSUE THREAD

**Issue by amr** [quran/quran.com-frontend-next#1791]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

If you are interested in reading about a particular topic or story in the Quran, more often than not, the relevant verses are spread between different Surahs.

I think it will be very valuable to allow readers to group bookmarks by some named topic. Technically speaking, users would have N bookmark groups where maybe one of them can be their "default"/main one. But they can create more topics/groups and when bookmarking, they can optionally choose to bookmark under a certain topic/group.

This should be similar to the concept of playlists found in media websites/applications.

If the feature proves useful, it can potentially evolve in the future to be shareable, where said topics/groups can be made public by their owner, and others can star/like/subscribe to them. Allowing those with more knowledge of the Quran to  make it easier for others to read verses that relate to a particular topic.

### Your purposed solution for this feature

I see two approaches here.

First one, is to build on top of the existing bookmarking feature, but make it so that there are multiple bookmark groups. One of them being the default. Users would be able to click on their profile, go to bookmarks, then create a new "Bookmark Group" (or "Bookmark Topic"). When they choose to bookmark a verse, the bookmark link would read "Bookmark", like it does today, but when you hover over it, a submenu expands with the list of bookmark groups. The user can click one of them instead. They should still be able to click "Bookmark" and have it go to the default group (current behavior).

Second one, is to use a labels system. That is unrelated to bookmarking. Users would simply get a new option to apply a label to a verse. The labels are private, and work in an autocomplete fashion. When a user opens the context (...) menu for a verse, they see a "Label" option, they click that and they are shown a submenu of the last 5 labels they used, with an additional auto-complete field that selects from their other previously used labels or creates a new one if they supply a new label. The user can then access their labels from their profile (or elsewhere), and click any label to see all the associated verses. This is perhaps simpler and arguably a bit more powerful than the first solution.

**Comment by osamasayed** [comment]
Alsalamu Alikum @amr Jazakum Allah Khairan for your suggestion. We have just released approach one where users can created a collection and add bookmarks to them.

<img width="1202" alt="Screen Shot 2022-09-26 at 8 17 23 PM" src="https://user-images.githubusercontent.com/15169499/192286631-2628948c-8271-4068-a1b8-a66703e85dd2.png">
<img width="236" alt="Screen Shot 2022-09-26 at 8 18 37 PM" src="https://user-images.githubusercontent.com/15169499/192286902-07b032b3-e6aa-4f79-bfff-c2c93d6cd372.png">
<img width="492" alt="Screen Shot 2022-09-26 at 8 18 53 PM" src="https://user-images.githubusercontent.com/15169499/192286941-921d28c6-e6ac-40a1-a6d6-3016e16a59fe.png">
