### ISSUE TITLE
[bug]: Layout breaks when selecting a new reciter on mobile sizing

### ISSUE THREAD

**Issue by HackintoshwithUbuntu** [quran/quran.com-frontend-next#1807]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

On the mobile layout, if a user is not scrolled all the way to the top of the page before selecting the settings menu and then attempting to change the reciter, the top part of the ui disappears.

### Relevant log output

```shell
A div changes from class: Drawer_container__v4a8e Drawer_containerOpen__pm7AS Drawer_right__kn0O_
to class: Drawer_container__v4a8e Drawer_navbarInvisible__sZbVq Drawer_containerOpen__pm7AS Drawer_right__kn0O_

the file: framework-d15b1307ec5e041b.js (https://quran.com/_next/static/chunks/framework-d15b1307ec5e041b.js) is called (however I'm not sure if its also called in the case that the ui doesn't break)
```

### Steps to reproduce

scroll down into a surah
![image](https://user-images.githubusercontent.com/64008512/191874304-642e0dd3-fa04-46b3-b941-c468ea90203a.png)

click on the settings menu

click on select reciter
![image](https://user-images.githubusercontent.com/64008512/191874358-15a54f07-26c7-480a-88c7-e7dd45266032.png)

then attempt to change reciter
![image](https://user-images.githubusercontent.com/64008512/191874379-15287df2-6d33-4f20-90ab-baa7d4580449.png)

However, If you reload and do not scroll down (or scroll to the top of the page if needed), then the issue will not occur

### Environment (please complete the following information) and Add any other context about this bug

OS: Android
Browser: Chrome
Version: 105.0.5

I also used to get this issue on safari in IOS and was able to replicate in the MS Edge debugger on windows

### Environment

Production(quran.com)

**Comment by kowrishankar** [comment]
Asalamu Alikum, I would like to contribute. I have already made a fix for this issue but i'm unable to push. Could you pls invite me as contributor?

**Comment by osamasayed** [comment]
> [kowrishankar](/kowrishankar)

Wa'likum Alsalam, already added you as a contributor. Jazak Allah Khairan for your effort!

**Comment by osamasayed** [comment]
> Asalamu Alikum, I would like to contribute. I have already made a fix for this issue but i'm unable to push. Could you pls invite me as contributor?

Wa'likum Alsalam, you will need to fork this repo, create your PR and create a merge request. I will take a look at your fix once your pushed it inshAllah. Jazak Allah Khairan for you contribution!

**Comment by kowrishankar** [comment]
Thanks, created a PR: https://github.com/quran/quran.com-frontend-next/pull/1811
