### ISSUE TITLE
[bug]: Un-selecting all translations doesn't reflect

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-next#1808]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When the current settings only have 1 translation, un-checking it doesn't remove it from the UI.

![Sep-24-2022 09-38-05](https://user-images.githubusercontent.com/15169499/192076739-a2f3e7dc-933e-4682-8f47-9cb41d81d7c2.gif)

### Steps to reproduce

1. Make sure you have default settings
2. Go to https://quran.com/1
3. Open the settings drawer and un-tick the only selected translation
4. The translation will still be visible even when the translation checkbox is un-ticked

### Environment (please complete the following information) and Add any other context about this bug

OS: Mac Monterey 12.5.1
Browser: Chrome
Version: 104.0.5112.101

### Environment

Production(quran.com)

**Comment by sksiyer** [comment]
Salam I think this would be a good first issue? If so please assign to me

**Comment by osamasayed** [comment]
> Salam I think this would be a good first issue? If so please assign to me

Wa'likum Alsalam, assigned to you already. JAK
