### ISSUE TITLE
[bug]: Tooltip content overflows

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-next#1810]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When tooltip text is long enough, it overflows.

<img width="886" alt="Screen Shot 2022-09-25 at 8 11 05 PM" src="https://user-images.githubusercontent.com/15169499/192145281-afc4a48a-d150-4012-b100-980e160e17aa.png">

### Steps to reproduce

1. Go to https://quran.com/27/14
2. Hover over the 3rd word of the Ayah (وَٱسْتَيْقَنَتْهَآ).
3. Tooltip text will overflow.

### Environment (please complete the following information) and Add any other context about this bug

OS: Mac Monterey 12.5.1
Browser: Chrome
Version: 104.0.5112.101

### Environment

Production(quran.com)

**Comment by kowrishankar** [comment]
Asalamu Alikum, Can I pick this up? If so, could you pls assign this to me?

**Comment by kowrishankar** [comment]
Here is the fix for the bug: https://github.com/quran/quran.com-frontend-next/pull/1812

**Comment by osamasayed** [comment]
> Here is the fix for the bug: #1812

Jazak Allah Kahiran @kowrishankar looks great and already merged!
