### ISSUE TITLE
[bug]: Tafsir showing "Something is wrong. Try again." error because there is no default language & mofasir

### ISSUE THREAD

**Issue by SpaRexDz1** [quran/quran.com-frontend-next#1825]
### Is there an existing issue for this?

- [x] There is no exsiting issue for this bug

### Describe the bug

When I click Tafsir on a verse, it shows "Something is wrong. Try again." error. But it was gone when I chose a language and a Mofasir.
EDIT: It seems like this problem isn't with English version of the site. Arabic, and maybe other languages.
![quran com_ar_19_2_tafsirs_ar-tafseer-al-qurtubi%22](https://user-images.githubusercontent.com/115227745/194545540-0efa5b20-9742-4932-97d5-5656cf94ab66.png)

### Steps to reproduce

1. Either read or translate some surah
2. select a verse
3. click tafsir
4. error might appear

### Environment (please complete the following information) and Add any other context about this bug

Browser: Chrome

### Environment

Production(quran.com)

**Comment by osamasayed** [comment]
@SpaRexDz1 JazakAllah Kahiran for reporting the issue. Unfortunately, I cannot reproduce it. Would it be possible to provide a video/GIF on how to reproduce it?

**Comment by SpaRexDz1** [comment]
> @SpaRexDz1 JazakAllah Kahiran for reporting the issue. Unfortunately, I cannot reproduce it. Would it be possible to provide a video/GIF on how to reproduce it?

[screen-capture.webm](https://user-images.githubusercontent.com/115227745/197638531-bdf53c99-267b-4bd0-8da0-da8db668040a.webm)

**Comment by osamasayed** [comment]
> > @SpaRexDz1 JazakAllah Kahiran for reporting the issue. Unfortunately, I cannot reproduce it. Would it be possible to provide a video/GIF on how to reproduce it?
> 
> [screen-capture.webm](https://user-images.githubusercontent.com/115227745/197638531-bdf53c99-267b-4bd0-8da0-da8db668040a.webm) I'd ask you to verify whether this problem appears when using the site with other languages. For me in English version of site has no problem

Thanks for the video you shared. I can reproduce now. Seems to be an issue with one specific Tafsir. If you check the url once you open the default Tafsir, it will be `https://quran.com/ar/2:255/tafsirs/ar-tafseer-al-qurtubi"` with an extra `"` at the end. Removing it fixes the issue. Sounds like an issue with the API will double check. JAK

**Comment by osamasayed** [comment]
> > > @SpaRexDz1 JazakAllah Kahiran for reporting the issue. Unfortunately, I cannot reproduce it. Would it be possible to provide a video/GIF on how to reproduce it?
> > 
> > 
> > [screen-capture.webm](https://user-images.githubusercontent.com/115227745/197638531-bdf53c99-267b-4bd0-8da0-da8db668040a.webm) I'd ask you to verify whether this problem appears when using the site with other languages. For me in English version of site has no problem
> 
> Thanks for the video you shared. I can reproduce now. Seems to be an issue with one specific Tafsir. If you check the url once you open the default Tafsir, it will be `https://quran.com/ar/2:255/tafsirs/ar-tafseer-al-qurtubi"` with an extra `"` at the end. Removing it fixes the issue. Sounds like an issue with the API will double check. JAK

Found the issue. Seems I added an extra [`"`](https://github.com/quran/quran.com-frontend-next/blob/0b54966049853fecc8e0d0b0b1c25997293d9ad7/src/redux/defaultSettings/locales/ar.ts#L5) by mistake. Will fix it today inshAllah

**Comment by osamasayed** [comment]
[Fixed](https://github.com/quran/quran.com-frontend-next/commit/5c34bb548dcdde7beb4798dde32ec2bd1b60cda9) and will be pushed to the live website in the upcoming release inshAllah

**Comment by SpaRexDz1** [comment]
May Allah bless you
