### ISSUE TITLE
[bug]: Bookmark not working in production 

### ISSUE THREAD

**Issue by sayamalvi** [quran/quran.com-frontend-next#1834]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When bookmarking an ayah a popup shows "Something went wrong. Please try again."

### Relevant log output

```shell
access to fetch at 'https://auth.quran.com/bookmarks/bookmark?mushafid=7&key=5&type=ayah&versenumber=19' from origin 'https://quran.com' has been blocked by cors policy: no 'access-control-allow-origin' header is present on the requested resource. if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with cors disabled.
```

### Steps to reproduce

Go to quran.com and open any Surah.
Click on three dots on the left side of ayah and click on Bookmark.
A popup will appear on the bottom right side.

### Environment (please complete the following information) and Add any other context about this bug

Windows 11
Brave
Version 1.45.118

### Environment

Production(quran.com)

**Comment by osamasayed** [comment]
@sayamalvi I cannot reproduce on production and I noticed that `mushafid` is an incorrect param name that we don't have in our codebase. it's `mushafId` and also as the CORS error suggests, we only accept connections from our internal domains which doesn't seem to be the case with the issue you have faced.
