### ISSUE TITLE
slack invitation

### ISSUE THREAD

**Issue by Abdullah-Alhariri** [quran/quran.com-frontend-next#1842]
### Summary

Salam alaykum.
I want to see the development of Quran.com
until I feel comfortable enough to contribute
[alhariri.abdu.2018@gmail.com](mailto:alhariri.abdu.2018@gmail.com)

**Comment by AyahRamahi** [comment]
There's a Discord server invitation link at the top of [this Readme](https://github.com/quran/quran.com-frontend-next/blob/master/README.md) file, I believe this is what you're looking for.
