### ISSUE TITLE
[question]: can i deploy on similar domain which i own?

### ISSUE THREAD

**Issue by KamalHunzai** [quran/quran.com-frontend-next#1846]
### Summary

Aslam alykum, I would like to deploy a copy of this codebase to a similar domain that i own. Would that be something i would be allowed to do? What would be the process ?
Thank you for you help and response.
Regards

**Comment by KamalHunzai** [comment]
@sharabash @mmahalwy @naveed-ahmad @ahmedre @

**Comment by osamasayed** [comment]
Wa'likum Alsalam, we have already [mentioned](https://github.com/quran/quran.com-frontend-next#how-to-contribute) in the repo guidelines that it's not allowed to copy the entire project. Please refer back to it. Jazak Allah Khairan
> We trust that you will not copy this idea/project, this is at the end for the sake of Allah and we all have good intentions while working with this project. But we must stress that copying the code/project is unacceptable.
