### ISSUE TITLE
Please Add Aasan Tarjuma Quran by mufti taqi usmani sahab 

### ISSUE THREAD

**Issue by umarumair** [quran/quran.com-frontend-next#1895]
It is a request by many urdu speakers from developers of quran.com to please include `Aasan Tarjuma Quran` by shaykh ul islam mufti taqi usmani 
And Please add `Maariful Quran Urdu` tafsir

**Comment by osamasayed** [comment]
Alsalmau Alikum, thanks for your request. We use feedback.quran.com for any content-related requests. You can up-vote this [request](https://feedback.quran.com/translation-and-reciter-requests/p/please-add-mufti-taqi-usmani-urdu-translation-1).
