### ISSUE TITLE
Not all footnotes have references in the Qur'an

### ISSUE THREAD

**Issue by validity-check** [quran/quran.com-frontend-next#190]
In Surah Al Fath, Ayah 29, the Mustafa Khattab translation has a footnote which references the Bible. The reference is taken as one from the Qur'an:
Footnote:
![image](https://user-images.githubusercontent.com/63739210/124974216-73bad280-e024-11eb-8e0a-257d6f17065b.png)
Taken as a reference from the Qur'an when clicked:
![image](https://user-images.githubusercontent.com/63739210/124974264-7fa69480-e024-11eb-8b07-cc481b86ea71.png)

May Allah reward you for your efforts regarding this application, it is one of my favourites.

**Comment by naveed-ahmad** [comment]
JazakAllah kharain for reporting this brother. Fixed on beta.quran.com
