### ISSUE TITLE
[feature]: Spacebar to pause

### ISSUE THREAD

**Issue by M-Arnone** [quran/quran.com-frontend-next#1907]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

[macOS Monterey]
When you're on the application, you're forced to pause the current recitation with tu button "Play/Pause" but we, as developers, hate use trackpad. So, why not add functionality to pause with the spacebar ? 
Thanks to everybody reading this,
Take care of you and your families. 

### Your purposed solution for this feature

To shorten it, copy Spotify.

**Comment by hazem3500** [comment]
[Kapture 2023-02-04 at 18.41.18.webm](https://user-images.githubusercontent.com/22430645/216779428-8bb75355-4bd3-4d03-95d1-b265ede985b9.webm)


Are you sure pressing `Space` doesn't play/pause the recitation for you? 🤔 

I've tested it on Chromium, MacOs and the `Space` and `Next/Prev Track` buttons are working, but the `Play/Pause` function button on the keyboard isn't 😅

**Comment by M-Arnone** [comment]
Again, wrong repo. I'm miserable ahahah..
I was talking about the macOS app but good to see that you have this bug too and that's not only my this time.

**Comment by hazem3500** [comment]
Hehe 😆, yup, I guess the `Play/Pause` function button needs a bit of an investigation 🔍 
But the `Space` button should be working 👍😄
