### ISSUE TITLE
[bug]: Audio not correctly in sync with text highlighting

### ISSUE THREAD

**Issue by gyenabubakar** [quran/quran.com-frontend-next#1919]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Salamu alaikum!

I was listening to Mishary Al-Afasy's recitation of Suratul Ankaboot, and at the 10th ayah, the audio and word highlighting went out of sync.

> Update: it seems this problem doesn't exist on [beta.quran.com](https://beta.quran.com).

### Steps to reproduce

1. Go to https://quran.com/29/10
2. Play the verse.

### Environment (please complete the following information) and Add any other context about this bug

**OS:** macOS Ventura (13.2.1)
**Browser:** Chrome
**Version:** 110.0.5481.100

### Environment

Production(quran.com)

**Comment by osamasayed** [comment]
Alsalamu Alikum @gyenabubakar, since this is a content issue and not a functionality issue, please submit it on https://feedback.quran.com/audio-issues. Jazak Allah Kahiran!
