### ISSUE TITLE
[feature]: Make floating buttons for Translation mode and Reading mode

### ISSUE THREAD

**Issue by Luciogi** [quran/quran.com-frontend-next#1924]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

As for now, Mode can be switched from start page of Surah/Chapter. In case of user want to see translation of translation of verse, then he has go scroll to start and click on" translation" button
which is so bad experience

### Your purposed solution for this feature

I would Like to see floating buttons to switch between modes

**Comment by shakib2018** [comment]
I believe related to this : https://feedback.quran.com/feature-requests/p/converting-between-reading-and-translation-in-middle-of-a-surah

**Comment by osamasayed** [comment]
This is planned soon inshaAllah
