### ISSUE TITLE
[question]:  Website interface langauge

### ISSUE THREAD

**Issue by GoRaN909** [quran/quran.com-frontend-next#1932]
### Summary

السَّلَاْمُ عَلَیْکُم وَ رَحْمَةُ اللّٰهِ وَ بَرَکَاْتُه

Hi brothers please I need some help can anyone tell me how can I add my native language Kurdish(کوردی) translation to main website [Quran.com](https://quran.com) Is just translating all strings on [../locales](https://github.com/quran/quran.com-frontend-next/tree/master/locales) is enough will it show in the list of languages if I start translate.

@naveed-ahmad @osamasayed

**Comment by osamasayed** [comment]
Wa'likum Alsalam, we use a service called Lokalise to manage translations that syncs with the locales directory in our repo. If you are interested, please message me on Discord (Osama Sayed#0504) and we can go through the steps on how to add Kurdish translations on Lokalise. Jazak Allah Khairan for wanting to help!
