### ISSUE TITLE
[bug]: Ar-R'ad reciter Khalifah Taniji play ayah 2 instead ayah 1

### ISSUE THREAD

**Issue by laptopmutia** [quran/quran.com-frontend-next#1934]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

[bug]: Ar-R'ad reciter Khalifah Taniji play ayah 2 instead ayah 1

### Steps to reproduce

go to https://quran.com/13
change reciter to Khalifah Taniji
press play at ayah 1 it play ayah 2 instead 1

### Environment (please complete the following information) and Add any other context about this bug

firefox and chrome 

### Environment

Production(quran.com)

**Comment by osamasayed** [comment]
Alslaamu Alikum, Jazakum Allah Kahiran for reporting. Please submit this issue on https://feedback.quran.com/audio-issues where audio-related issues get handled.
