### ISSUE TITLE
[bug]: Clicking on verses doesn't do anything

### ISSUE THREAD

**Issue by yosefbeder** [quran/quran.com-frontend-next#1937]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When I click on a verse, I expect to see a popup containing some actions like listening and reading tafsir... etc.
I used to have a windows laptop and everything was working fine on Edge, but now I brought a mac laptop and It's not working on Safari or Edge.

### Steps to reproduce

1. Go to any page in reading mode.
2. Click on any verse.

### Environment (please complete the following information) and Add any other context about this bug

OS: macOS Ventura 13.3
Browser: Safari 16.4 and Microsoft Edge 111.0.1661.62 (Official build) (arm64)
Version:

### Environment

Production(quran.com)

**Comment by ninearif** [comment]
did you mean this tooltip? 
![image](https://user-images.githubusercontent.com/3044249/230706295-4fcdb8eb-670c-4ef6-9106-5d83dfaad28c.png)


Could you please check if you checked the **Tooltip** option under the **Display** setting? this should be checked to see the tooltip

![image](https://user-images.githubusercontent.com/3044249/230706276-c8e34d21-c9d1-4aba-b42a-e661b471fa33.png)

**Comment by yosefbeder** [comment]
Yes, I do thanks
