### ISSUE TITLE
[feature]: Thai locales update

### ISSUE THREAD

**Issue by ninearif** [quran/quran.com-frontend-next#1941]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

I've made an update on a translation for Thai language via `QDC Next` on **Lokalise**. 
here is what has been fixed in the latest update

- fix a bunch of incorrectly translated word
- fix untranslated word
- improve the translation for more clarification

### Your purposed solution for this feature

Check out the latest updated for Thai on **Lokalise**

**Comment by osamasayed** [comment]
Jakaum Allahu Khairan @ninearif for you efforts. Updates will be available on the live website in the upcoming release inshAllah.

**Comment by ninearif** [comment]
@osamasayed I see there're two branches on Lokalise I've made the change on the `master` branch.
 I'm not pretty sure about what `strikes` is. is it a kind of staging branch?

**Comment by osamasayed** [comment]
> @osamasayed I see there're two branches on Lokalise I've made the change on the `master` branch. I'm not pretty sure about what `strikes` is. is it a kind of staging branch?

No worries `master` is the right branch. `streaks` is another feature that is not ready to merge yet. But you picked the right branch. Jazak Allah Kahiran!
