### ISSUE TITLE
[bug]: Hovering over words won't translate them in Edge?

### ISSUE THREAD

**Issue by Arsalan-Zahid** [quran/quran.com-frontend-next#1949]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Assalamualaikum wa rahmatullahi wa barakatuhu,

Hovering over words in edge won't show a translation.  It will, however, turn blue, and clicking on it will play a sound.
Interestingly, hovering over words in previous.quran.com works, but not in quran.com .

Jazakallahkhair.

### Relevant log output

```shell
No logs were found in the console.
```

### Steps to reproduce

1. Go to any quran page on Edge
2. Hover over a word

### Environment (please complete the following information) and Add any other context about this bug

OS: Windows 11
Browser: Edge
Edge Version: 112.0.1722.39

### Environment

Production(quran.com)

**Comment by shakib2018** [comment]
did you check this box in settings? 
![Web capture_16-4-2023_15198_quran com](https://user-images.githubusercontent.com/86146710/232289196-c9f558a6-16b1-49a6-bfb6-031cc1739a28.jpeg)

**Comment by Arsalan-Zahid** [comment]
Sorry about that, jazakallahkhair
