### ISSUE TITLE
[bug]: Surah icons don't update after sorting by descending in Revelation Order tab

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-next#1957]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Surah icons don't change after changing the sorting order of the Revelation Order tab.

![Apr-27-2023 14-23-38](https://user-images.githubusercontent.com/15169499/234860985-4b24d68b-7916-4722-9d18-31783965b9db.gif)

### Steps to reproduce

1. Go to [quran.com](http://quran.com/).
2. Scroll down until you reach the chapter list.
3. Click the 'Revelation Order' tab.
4. Click 'SORT BY:ASCENDING'.
5. You'll see that the chapter icons (the Arabic chapter name) stays the same i.e. al-Nasr has the icon of al-'Alaq, al-Tawbah has the icon of al-Qalam, etc.

### Environment (please complete the following information) and Add any other context about this bug

OS: MacOs Monetery 12.6.4
Browser: Chrome
Version: 112.0.5615.137

### Environment

Production(quran.com)

**Comment by ThatSameer** [comment]
Asalaamualaikum,
Is it ok if I take this issue?

**Comment by osamasayed** [comment]
> Asalaamualaikum, Is it ok if I take this issue?

Wa'likum Alslaam, yes sure. Jazak Allahu Khairan!
