### ISSUE TITLE
[feature]: add audio volume control

### ISSUE THREAD

**Issue by XamzatJR** [quran/quran.com-frontend-next#1970]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

I now that you can turn up/down audio volume in OS volume mixer but I don't wanna do it every time when I visit this website. It would be better if there was audio volume control that let us change the audio's volume not the whole system (or browser).

### Your purposed solution for this feature

Add a custom volume control component for screens wider than 768px.

**Comment by sksiyer** [comment]
Salaam,

Please assign this to me, I've created a PR https://github.com/quran/quran.com-frontend-next/pull/2005
Have a look :) 

Jazak'Allah khair

**Comment by osamasayed** [comment]
> Salaam,
> 
> Please assign this to me, I've created a PR #2005 Have a look :)
> 
> Jazak'Allah khair

Already assigned to you. Jazakum Allahu Khairan sister for your PR! We will take a look inshAllah
