### ISSUE TITLE
Add Husky as a pre-commit hook

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend-next#20]
https://www.npmjs.com/package/husky
- Run prettier before committing

**Comment by nabeel-** [comment]
Have you thought about setting up [a github action](https://github.com/features/actions) to run tests or linting for PRs/commits? In addition to Husky for pre-commit hooks, we can have the PR build/run tests without having to set up travis/jenkins/another CI tool.

**Comment by mmahalwy** [comment]
Yes. I'd like to. Can you own it @nabeel- ? I can give you collaborator access.

**Comment by nabeel-** [comment]
Of course - happy to own it!
