### ISSUE TITLE
[feature]: footnote number identifier

### ISSUE THREAD

**Issue by Shaleel** [quran/quran.com-frontend-next#2004]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

If a footnote is having large content it gets confusing for user as to which particular footnote is opened.

### Your purposed solution for this feature

A simple solution could be to just add footnote number in the heading of the footnote only
<img width="804" alt="image" src="https://github.com/quran/quran.com-frontend-next/assets/64775875/d89c5f68-c300-48d0-9385-9bca119803cc">

**Comment by Mizab1** [comment]
Assalamu’alaikum warahmatullahi wabarakatuh,

Can I implement this feature?

**Comment by osamasayed** [comment]
> Assalamu’alaikum warahmatullahi wabarakatuh,
> 
> Can I implement this feature?

Sure, would be great to. Feel free to create a PR. Jazakum Allahu Khairan!
