### ISSUE TITLE
[bug]: Storybook link is broken 

### ISSUE THREAD

**Issue by waghydjemy** [quran/quran.com-frontend-next#2007]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Salam Alaikum

Storybook link is broken https://quran.github.io/quran.com-frontend-next/storybook/master

I did not see a similar bug, if it present feel free to flag this as duplicate

### Relevant log output

```shell
404 page
```

### Steps to reproduce

Go to https://quran.github.io/quran.com-frontend-next/storybook/master check that the link is not working

### Environment (please complete the following information) and Add any other context about this bug

Chrome, edge

### Environment

Production(quran.com)

**Comment by talal-najam** [comment]
If I'm looking in the right place, the pipelines seem to be failing.

https://github.com/quran/quran.com-frontend-next/actions/workflows/build-storybook.yml

**Comment by osamasayed** [comment]
Alsalamu Alikum brothers, this issue is related/a duplicate of #1882, #1906 and #1735. We will be re-adding Storybook inshAllah. Jazakum Allahu Khairan.

**Comment by waghydjemy** [comment]
Thanks for the reply @osamasayed, I will close this for now
