### ISSUE TITLE
[bug]: 38:45 tooltip hover translation is incorrect

### ISSUE THREAD

**Issue by Arsalan-Zahid** [quran/quran.com-frontend-next#2008]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Assalamualaikum wa rahmatullahi wa barakatuhu,

<img width="550" alt="image" src="https://github.com/quran/quran.com-frontend-next/assets/50848963/7b855b16-1c88-4bb1-a8dd-2fa8b1748e40">

It should Jacob or Yaqub, not Ayyub 

### Relevant log output

```shell
None
```

### Steps to reproduce

1. Go to https://quran.com/38/45
2. Hover over yaqub

### Environment (please complete the following information) and Add any other context about this bug

OS: Win 11
Browser: Edge
Version 114.0.1823.82 (Official build) (64-bit)

### Environment

Staging(next.quran.com)

**Comment by Arsalan-Zahid** [comment]
Just realized I selected the wrong environment; it's regular quran.com

**Comment by talal-najam** [comment]
The API response returns 'Ayyub' for the text 'يَعْقُوبَ'. Seems to be English translation-language specific issue. Urdu, Bengali, Farsi etc. seem okay.

simplified URL - https://staging.quran.com/api/qdc/verses/by_chapter/38?words=true&page=45&per_page=1

Full API call - https://staging.quran.com/api/qdc/verses/by_chapter/38?words=true&translation_fields=resource_name%2Clanguage_id&per_page=1&fields=text_uthmani%2Cchapter_id%2Chizb_number%2Ctext_imlaei_simple&translations=131&reciter=7&word_translation_language=en&page=45&word_fields=verse_key%2Cverse_id%2Cpage_number%2Clocation%2Ctext_uthmani%2Ccode_v1%2Cqpc_uthmani_hafs&mushaf=2
