### ISSUE TITLE
[bug]: Surah Al-Waqi'ah

### ISSUE THREAD

**Issue by mad1m** [quran/quran.com-frontend-next#2009]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Surah Al-Waqi'ah (56), Default Settings (Mishari Rashid al-`Afasy)

After some verses, it starts to play incorrect verses (from the same Surah).

i don't think it's a content-related bug, as it occurs randomly and is not specific to particular verses, and the downloaded audio (56.mp3) has no issues, also it seems that it only affects Chromium-based browsers.
i don't know if only this Surah has this issue, and the fact it works fine in Firefox browser make it more confusing.

### Steps to reproduce

1. Go to https://quran.com/56
2. Scroll down, play last verses, For example, play 56:89, it may or may not play incorrect verse

or
1. Go to https://quran.com/56
2. Play Audio
3. Wait, at some point it starts to play incorrect verse

Also try new session (Incognito window)

### Environment (please complete the following information) and Add any other context about this bug

Browsers i tested that have this issue:

- Chrome 115.0.5790.110, Windows 10
- Chrome 115.0.5790.138, Android 12.1
- Edge 115.0.1901.188, Windows 10

Browsers i tested that doesn't have this issue:

- Firefox 115.0.3, Windows 10
- Firefox 115.2.1, Android 12.1

### Environment

Production(quran.com)

**Comment by mad1m** [comment]
![image](https://github.com/quran/quran.com-frontend-next/assets/141098566/b8e1bd3e-71b6-418a-95a1-91487707be88)
looks like the issue has been happening since July 17 or even earlier

**Comment by osamasayed** [comment]
Alsalamu Alikum, since this is not a code issue, please report it on https://feedback.quran.com/audio-issues where the people responsible for audio will take a look inshAllah. Jazak Allahu Khairan!

**Comment by mad1m** [comment]
> Alsalamu Alikum, since this is not a code issue, please report it on https://feedback.quran.com/audio-issues where the people responsible for audio will take a look inshAllah. Jazak Allahu Khairan!

How do you know it's not a code issue, the issue only affects Chromium-based browsers not Firefox.

**Comment by osamasayed** [comment]
> > Alsalamu Alikum, since this is not a code issue, please report it on https://feedback.quran.com/audio-issues where the people responsible for audio will take a look inshAllah. Jazak Allahu Khairan!
> 
> @osamasayed How do you know it's not a code issue, the issue only affects Chromium-based browsers not Firefox.

If there is an audio issue that only applies to a specific group of verses and not the rest of the Quran, most definitely it's not a code issue, otherwise, we should see it happening everywhere else. Frontend code does not have a specific handler for Surah Al-Waqi'ah and works the same for every Surah and Ayah. Our audio team are the ones to verify this. Jazak Allahu Khairan.
