### ISSUE TITLE
[bug]: Too long file name causing a windows extraction error

### ISSUE THREAD

**Issue by amrmoustafa123** [quran/quran.com-frontend-next#2030]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When I try to clone the repository locally I get an error saying that the file name of t she [ReflectionSurahAndAyahSelection.module.scss](https://github.com/quran/quran.com-frontend-next/blob/master/src/components/QuranReader/ReflectionView/ReflectionBodyContainer/ReflectionSurahAndAyahSelection/ReflectionSurahAndAyahSelection.module.scss) file is too long on Windows 11.

### Steps to reproduce

1. Download the zip file of the repo.
2. Try to extract it on a Windows 10/11 Machine.

### Environment (please complete the following information) and Add any other context about this bug

OS: Windows 11

### Environment

Production(quran.com)

**Comment by nasserakhter-ma** [comment]
Works for me using the built-in file explorer extracting or 7-zip.

**Comment by mohdabidansari** [comment]
Even works for me. You can try to extract using WinRAR.
