### ISSUE TITLE
[bug]: Broken Voice Search For Tarteel

### ISSUE THREAD

**Issue by wajeehmisbahkhan** [quran/quran.com-frontend-next#2056]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Currently the voice search seems to be converting voice to speech but never executing the search:
![image](https://github.com/quran/quran.com-frontend-next/assets/37481915/8df776a8-9f19-4eec-88c3-c1b2e88ebc72)

I've tried clicking on the mic button with no luck. I also noticed the following issue mentions that the voice search is broken:
https://github.com/quran/quran.com-frontend-next/issues/735

This seems to be quite an old issue while I remember using voice search some time back and it was working correctly so I'm assuming it may be referring to something else which was fixed (or I may be hallucinating memories of a functioning voice search).

### Steps to reproduce

1. Go to the voice search
2. Recite an ayah
3. Voice gets converted to text but no way to execute the search

### Environment (please complete the following information) and Add any other context about this bug

OS: Mac
Browser: Brave
Version: 1.61.101

### Environment

Production(quran.com)

**Comment by mmmoussa** [comment]
This issue has now been resolved, thanks for reporting! @osamasayed please close.
