### ISSUE TITLE
[bug]: "Previous Surah" and "Next Surah" buttons are broken on alot of pages

### ISSUE THREAD

**Issue by professorparabellum** [quran/quran.com-frontend-next#2064]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

https://github.com/quran/quran.com-frontend-next/assets/116983354/70125b04-e33c-46f8-ab99-f1201cfac131

For example, the next Surah button in Surat Al-Fil leads you to Surat Al-Falaq, and the previous Surah button takes you to Surat Al-kafirun.

### Steps to reproduce

1. Go to any Surah
2. Try to navigate using the buttons at the very bottom of the page
3. Most of the time it'll take you to the wrong surah

### Environment (please complete the following information) and Add any other context about this bug

OS: Windows 10 Pro
Browser: Firefox
Version: 121.0

This bug occurred to me a few months back on my phone (iphone X on ios16 using Safari) but i thought nothing of it.

### Environment

Production(quran.com)

**Comment by rzmk** [comment]
Just an observation it looks like it's changing the surah based on the revelation order option. If you look right above the buttons in your video it says "Click here to return to the default ordering".

![image](https://github.com/quran/quran.com-frontend-next/assets/30333942/249587e8-d9d2-404e-aac5-3f6bae6dce72)

**Comment by professorparabellum** [comment]
Thats what it is, im so stupid 🤦‍♂️ JazakAllahkhair
