### ISSUE TITLE
[bug]: text not loading when opening through bookmark

### ISSUE THREAD

**Issue by njmulsqb** [quran/quran.com-frontend-next#2081]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Aoa,

While opening the quran through bookmark, only the bookmarked verse gets loaded and the rest of the verses dont load
<img width="1408" alt="image" src="https://github.com/quran/quran.com-frontend-next/assets/47940898/b6590d5d-5757-4bdf-b26d-a46ff74ab952">

This wasnt happening with me before and is a recent issue

### Steps to reproduce

1. Open a bookmarked verse i.e. Ahzab 33:22
2. Click on Continue

### Environment (please complete the following information) and Add any other context about this bug

OS: MacOS
Browser: Firefox
Version: Latest

### Environment

Production(quran.com)

**Comment by Wajid2001** [comment]
![image](https://github.com/quran/quran.com-frontend-next/assets/67428865/ab0363f0-d32e-46dc-8edb-219a242b5b78)
![image](https://github.com/quran/quran.com-frontend-next/assets/67428865/d2720248-bc95-497e-a961-f862ee258b24)


Unable to reproduce the bug. When we goto the bookmarked verse, only verse is shown as expected, and when the continue button below the ayat is click I am able to load prev and next ayats.

**Comment by Wajid2001** [comment]
![image](https://github.com/quran/quran.com-frontend-next/assets/67428865/4260f4dd-c7fb-49df-a0be-d479ae0e5ef8)
![image](https://github.com/quran/quran.com-frontend-next/assets/67428865/4f50b5fc-3870-48bd-988a-ebdcc9b31094)
![image](https://github.com/quran/quran.com-frontend-next/assets/67428865/cc36e99c-b426-4d8b-b16a-1e1bc4e4c5c4)

Unable to reproduce the bug. When the bookmarked ayat is clicked, that only ayat is opened. and when the user clicks on the  continue button its redirected to reading continuation page, where it can scroll to view previous or next verse.


**ENV**
OS: Windows
Browser: Firefox
Version: 122.0.1 (64-bit)

**Comment by njmulsqb** [comment]
I am still facing this issue on firefox (macOS)

**Comment by Wajid2001** [comment]
Seems like Mac specific issue, let's wait for someone with mac

**Comment by haffi96** [comment]
Wasn't able to replicate this on MacOS (Tried on Firefox and Arc browser). I see the same flow as mentioned above 

![image](https://github.com/quran/quran.com-frontend-next/assets/53666594/61e67e3b-a5df-4c6e-ae06-2b6b5289e11c)

![image](https://github.com/quran/quran.com-frontend-next/assets/53666594/fec0555d-c51e-4b48-9c52-8e77d1699b54)

![image](https://github.com/quran/quran.com-frontend-next/assets/53666594/c90c71f3-6a69-42ca-8524-829f49c62bcb)

ENV
OS: MacOS
Browser: Firefox
Version: 123.0.1 (64-bit)
