### ISSUE TITLE
[bug]: 500 error when tracking progress

### ISSUE THREAD

**Issue by 3rg1s** [quran/quran.com-frontend-next#2109]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

/activity-days endpoint throws 500 error when reading a verse.
This also happens when trying to manually add a reading activity

### Relevant log output

```shell
Payload sent: {"ranges":["1:5-1:7"],"seconds":1}


BE Response:
{
    "success": false,
    "error": {
        "code": "ServerError",
        "message": "Something went wrong"
    }
}
```

### Steps to reproduce

1. Visit quran.com
2. Open Al FATIHA
3. scroll through the ayats

### Environment (please complete the following information) and Add any other context about this bug

OS: Macbook
Browser: Chrome
Version: Version 122.0.6261.112 (Official Build) (arm64)

### Environment

Production(quran.com)

**Comment by osamasayed** [comment]
Jazak Allahu khairan @3rg1s for raising this issue, it's being investigated.

**Comment by 3rg1s** [comment]
@osamasayed salam aleykum, shall we close this ticket since I see the error, is not reproducible anymore.

**Comment by osamasayed** [comment]
> @osamasayed salam aleykum, shall we close this ticket since I see the error, is not reproducible anymore.

Yes Alhamdulelah it was resolved.
