### ISSUE TITLE
[feature]: Shareable image(s) for an Ayah

### ISSUE THREAD

**Issue by craxrev** [quran/quran.com-frontend-next#2204]
### Is there an existing issue for this feature?

- [X] There is no exsiting issue for this feature

### Summary

Hello, I've trying find anything to help with, I stumbled upon an PR (#2090) that seems stagnant, also I noticed you started integrating a new feature on this [branch](https://github.com/quran/quran.com-frontend-next/tree/image-generator) for custom video/image generation ..

### Your purposed solution for this feature

Should we close that PR and continue working on the new video/image generation feature? otherwise I can jump and continue the work done so far on that PR, I see a lot of screenshots posted on social media from quran.com and having such a feature separate from the video/image generation, would be useful and very quick to interact with

What do you think?

**Comment by osamasayed** [comment]
JAK Khairan for your suggestion. I already closed the old PR and we will stick with the media generator which will be released shortly inshaAllah
