### ISSUE TITLE
[bug]: Repeating verse does not work

### ISSUE THREAD

**Issue by 3rg1s** [quran/quran.com-frontend-next#2210]
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

Repeating a verse does not work on prod environment when logged in. Backend endpoint (
https://auth.quran.com/preferences) seems to return 422 Unprocessable Content. 

Request Headers:
![image](https://github.com/user-attachments/assets/e3a63af8-2883-4a11-a4a9-5674f0878439)

Response Headers:
![image](https://github.com/user-attachments/assets/ea46f698-a004-48c3-8b55-9f0b49073d6a)

### Steps to reproduce

1. Log in with your account
2. Chose a surah
3. Click the three dots
4. Click Repeat Verse
5. Click Start Playing

### Environment (please complete the following information) and Add any other context about this bug

OS: MacOS Sequoia
Browser: Google Chrome 
Version: 129.0.6668.58 (Official Build) (arm64)

### Environment

Production(quran.com)

**Comment by osamasayed** [comment]
Alsalamu Alikum @3rg1s this issue has been fixed, Jazak Allahu Kahiran for reporting it!

**Comment by 3rg1s** [comment]
Hey, @osamasayed thank you for that. Can you please shortly describe what was the issue, and how you fixed it.

**Comment by osamasayed** [comment]
> Hey, @osamasayed thank you for that. Can you please shortly describe what was the issue, and how you fixed it.

We added tighter validations to our backend APIs but there was a bug in related to repeat settings that we fixed. Your not that it's for logged in users helped us debug fast. Jazak Allahu Khairan!
