### ISSUE TITLE
Reduce the CLS of the Home & Surah pages

### ISSUE THREAD

**Issue by Nasiff** [quran/quran.com-frontend-next#268]
This address will track the progress of reducing the CLS (Cumulative Layout Shift) of the Home & Surah pages.

**Comment by osamasayed** [comment]
Alhamdulelah the CLS for the homepage is now [`0`](https://pagespeed.web.dev/report?url=https%3A%2F%2Fquran.com%2F)

<img width="470" alt="Screen Shot 2022-08-26 at 6 03 14 AM" src="https://user-images.githubusercontent.com/15169499/186783579-6c1860ce-0222-46aa-93ee-00df24b95c7b.png">
