### ISSUE TITLE
Setup storybook to deploy to github pages or vercel

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend-next#28]
We'd like to deploy storybook stories into a preview website.

**Comment by Anasss** [comment]
ASA 👋 
I can take care of this!
We can use https://github.com/storybookjs/storybook-deployer and add it to the GH actions pipeline!

**Comment by Anasss** [comment]
PR created: https://github.com/quran/quran.com-frontend-next/pull/42
