### ISSUE TITLE
After playing the Verse, could not pick and replay certain part of the Verse.

### ISSUE THREAD

**Issue by inspirationjon** [quran/quran.com-frontend-next#294]
https://user-images.githubusercontent.com/63994441/130404645-86600323-f52b-47da-a70a-ee23c58c1057.png

**Comment by osamasayed** [comment]
Alsalamu Alikum @inspirationjon the screenshot you posted is related to our [old version](https://previous.quran.com) of the website. This issue is not happening on https://quran.com. Jazak Allah Khairan for reporting the issue!
