### ISSUE TITLE
close button text color don't change

### ISSUE THREAD

**Issue by mikoaruna** [quran/quran.com-frontend-next#299]
close button text don't change if i change theme to dark in settings popup
![photo6136332424653681230](https://user-images.githubusercontent.com/72701029/130560075-128ae6ac-112e-446a-a172-450281c7f837.jpg)

**Comment by osamasayed** [comment]
Al Salamu Alikum @mikoaruna , we have updated our UI and I believe this issue has been resolved. You can have a look and let us know if it still persists. Jazaka Allah Khairan for reporting.
