### ISSUE TITLE
Highlighting Ayats not working properly

### ISSUE THREAD

**Issue by ahmadmustafaanis** [quran/quran.com-frontend-next#36]
I am trying to copy some verses but unable to. Check this video to understand.

![ezgif-6-b637f0981902](https://user-images.githubusercontent.com/47111429/84657798-49383c00-af2e-11ea-8a3e-c87a1c2b4bde.gif)

**Comment by mmahalwy** [comment]
@ahmadmustafaanis can you change the issue title to something more specific?
