### ISSUE TITLE
First time changing font size showing `NaN`

### ISSUE THREAD

**Issue by Kamrulhasan12345** [quran/quran.com-frontend-next#373]
Assalamu'alaikum wa rahmatullahi wa barakatuh. 
**Name of the bug:** Font size bug

**Expected behaviour:** Change the font size perfectly

**But now showing:** Shows NaN, when changing the font size first time. But if I reload and try again, then it perfectly changes font size. 

**Steps to reproduce:**

1.  Clear caches for next.quran.com
2.  Then go to a surah
3. Try changing the font size of the arabic text first
4.  You will see NaN
5.  Reload and try again
6.  Now you will see changing font correctly, but now for the translation font size, same steps again

**Screenshots:**
before reloading:
![image](https://user-images.githubusercontent.com/32530625/132087113-5701fdd7-09b7-4f38-a9e1-de08b07f78f7.png)
after reloading: 
![image](https://user-images.githubusercontent.com/32530625/132087145-f2c12fc2-3e89-4765-846b-1c6635476bbc.png)

 **Additional enhancements**: After reloading and pressing on increase for the first time, font size shows 1 but if you don't click, font size shows nothing. It should show 1 basically.

**Comment by tifa2UP** [comment]
Assalamu alaikum,

Thank you for reporting the bug. Was it your first time using the website, or did you use it once before? We recently introduced a breaking change to the local storage schema. 

If you didn't use the website before, can you send me a copy of your local storage data. You can get through chrome developer tools -> application -> local storage. 

JAK

**Comment by Kamrulhasan12345** [comment]
Wa'alaikum as salam,

Here is the data: 
```json
{"quranReaderStyles":"{\"translationFontSize\":1,\"tafsirFontSize\":1,\"quranTextFontSize\":2,\"quranTextLineHeight\":3,\"quranTextLetterSpacing\":0,\"quranFont\":\"qpc_uthmani_hafs\",\"letterSpacingMultiplier\":1,\"quranTextFontScale\":4,\"translationFontScale\":1}","readingPreferences":"{\"readingPreference\":\"translation\",\"showWordByWordTranslation\":false,\"selectedWordByWordTranslation\":20,\"showWordByWordTransliteration\":false,\"selectedWordByWordTransliteration\":12,\"showTooltipFor\":[\"translation\"]}","translations":"{\"selectedTranslations\":[85,203],\"isUsingDefaultTranslations\":false}","theme":"{\"type\":\"system\"}","tafsirs":"{\"selectedTafsirs\":[168],\"isUsingDefaultTafsirs\":false}","bookmarks":"{\"bookmarkedVerses\":{}}","_persist":"{\"version\":1,\"rehydrated\":true}"}
```
for `persist:root` key

But now font size changing works correctly. I think most probably code does not function properly if it does not find any value for a specific thing in the local storage. I also faced some other issue at the first time visit (not now anymore), like blurred image on the homepage not loading, but after reloading, it worked.

May Allah reward you for investing time in this project!

**Comment by Kamrulhasan12345** [comment]
Now I remember that I went to the site before and understood the reason. Jazakallahu khairan for helping me figuring this out!

**Comment by tifa2UP** [comment]
Perfect, please do let us know if you experience any other issues.
