### ISSUE TITLE
Search filter not working

### ISSUE THREAD

**Issue by Kamrulhasan12345** [quran/quran.com-frontend-next#386]
Assalamu'alaikum wa rahmatullahi wa barakatuh.

**Name of the bug**: Search filter bug

**Expected behaviour**: Add the selected translation the filter list and FIlter the search results with the specific translation

**But now showing**: Cannot select a translation, the items don't function on click.

**Steps to reproduce**:

1. Search for a keyword
2. Try to select a translation filter
3. Now you will see the translation filter does not add to the filter list

**Video**:
https://user-images.githubusercontent.com/32530625/132116403-0d2672c3-6cbc-435d-bdba-38dd023628a0.mp4

Jazakallahu khairan

**Comment by osamasayed** [comment]
Wa'likum Al Salam @Kamrulhasan12345 , I believe the issue you reported above has been solved. Please try again and let us know if the issue still persists. Jazak Allah Khairan for reporting.

**Comment by Kamrulhasan12345** [comment]
I guessed that it would be something like multiple selected like the following the settings:
![image](https://user-images.githubusercontent.com/32530625/132284423-47fd0325-fb42-4815-b5b6-ecd776d94497.png)

But yes, I can now select a single translation

Jazakallahu khairan for reminding for me.

**Comment by osamasayed** [comment]
> I guessed that it would be something like multiple selected like the following the settings:
> ![image](https://user-images.githubusercontent.com/32530625/132284423-47fd0325-fb42-4815-b5b6-ecd776d94497.png)
> 
> But yes, I can now select a single translation
> 
> Jazakallahu khairan for reminding for me.

InshaAllah we will add this in the future so Search will support multiple translations and languages. Will close this issue. Jazak Allah Khairan.

**Comment by Kamrulhasan12345** [comment]
In Shaa Allah

Jazakallahu khairan for your efforts in this project.
