### ISSUE TITLE
Slack Channel Request

### ISSUE THREAD

**Issue by segmentationfaulter** [quran/quran.com-frontend-next#40]
ASA, can anybody please add me to the slack channel. My email address is: muhammadsackib@gmail.com

**Comment by Anasss** [comment]
ASA, could you please add me as well: anas.rach@gmail.com

**Comment by mmahalwy** [comment]
@segmentationfaulter @Anasss I added this: https://join.slack.com/t/quran/shared_invite/zt-fepnm2rp-TDTHcUpmgXQ2lt207pd9MA. Feel free to sign up there
