### ISSUE TITLE
Remove unused dependencies 

### ISSUE THREAD

**Issue by tifa2UP** [quran/quran.com-frontend-next#53]
The following dependencies are not used by codebase: 

```
"qs": "^6.9.2",
"react-dom": "^16.13.1",
"react-use": "^13.27.0",
"storybook-styled-components": "^1.1.4",
"styled-breakpoints": "^8.1.0",
```

Happy to create a PR to clean them and re-add them as we need them down the line

**Comment by nabeel-** [comment]
+1 for cleanup! One thing to note is that `react-dom` is actually a [peer dependency of `next`](https://github.com/vercel/next.js/blob/canary/packages/next/package.json#L114) so we should leave it installed to satisfy that requirement.

**Comment by mmahalwy** [comment]
I think we will use:
```
REQUIRED:
"styled-breakpoints": "^8.1.0",
MAYBE: 
"react-use": "^13.27.0",
"qs": "^6.9.2",
```

**Comment by cahitbeyaz** [comment]
as update
depcheck reports following:

**Unused dependencies**
* @radix-ui/react-polymorphic
* @radix-ui/react-visually-hidden
Unused devDependencies
* @storybook/addon-a11y
* @storybook/addon-actions
* @storybook/addon-essentials
* @storybook/addon-links
* @storybook/builder-webpack5
* @storybook/manager-webpack5
* @storybook/preset-scss
* @testing-library/jest-dom
* @types/node
* @types/react-dom
* @types/wicg-mediasession
* awesome-typescript-loader
* babel-loader
* babel-plugin-polyfill-corejs2
* babel-plugin-polyfill-regenerator
* eslint-config-next
* react-docgen-typescript-loader
* sass-loader
* stylelint-prettier
* stylelint-scss
* typescript
Missing dependencies
* types: .\tests\mocks\words.ts
* @storybook/addon-storyshots: .\src\storyshots.test.ts
* src: .\src\utils\api.ts
* mode: .\src\styles\themes\_dark.scss
* breakpoints: .\src\pages\search.module.scss
* utility: .\src\components\Verse\VerseText.module.scss
* i: .\src\components\dls\QuranWord\GlyphWord.module.scss
* generate-words: .\src\components\dls\QuranWord\GlyphWord.module.scss
* chapter-id: .\src\components\chapters\ChapterIcon\ChapterIcon.module.scss
* generate-chapters-glyphs: .\src\components\chapters\ChapterIcon\ChapterIcon.module.scss
