### ISSUE TITLE
Sounds do not work for the Surahs(chapters) which has more then ten ayats(verses)

### ISSUE THREAD

**Issue by Mirodil** [quran/quran.com-frontend-next#59]
Hello,

Thank you for the project. There is an issue in the playing sounds which was loaded dynamically(lazy loading). Here is steps to reproduce:

- Open any Surahs(chapters) which has more then 10 ayats(verses)
- Scroll down to any ayats(verses) grater then 10
- Hit "Play" button on the left
- As you can see it cannot play it as it was not loaded
![image](https://user-images.githubusercontent.com/1898801/86148116-398d2b80-bac8-11ea-999f-33f2dcb3588e.png)

This issue is reproducible in the chrome and the firefox.

**Comment by mmahalwy** [comment]
Hi, this is the old quran.com. Let's keep issues here for new version

**Comment by Mirodil** [comment]
@mmahalwy When is this fix going to be published? because I still see those issues(and when focus changing to next verses is wired)
