### ISSUE TITLE
Create mobile app page

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend-next#6]
Designs here: http://beta.quran.com/pages/apps

**Comment by Shemsedin** [comment]
@mmahalwy  I will take this in sha Allah.

**Comment by Shemsedin** [comment]
@mmahalwy I have done a PR please see https://github.com/quran/quran.com-frontend-next/pull/100

**Comment by tifa2UP** [comment]
Chatted with @Shemsedin on his PR. This issue is also blocked on the design. I'm gonna close it until we have the new specs
