### ISSUE TITLE
Chapters display only the first 10 verses

### ISSUE THREAD

**Issue by Kafiil** [quran/quran.com-frontend-next#69]
Assalamu Alaikom, and great work !

TLDR; I know this is not a bug, I'm just curious how this is achieved.

I'm curious, how does the chapters display max 10 verses ? ( I think this is for test purposes) but I cloned the repo and browsed the code and couldn't figure out how this is accomplished.

When I request for a chapter, ex: 46 by the GET request `http://api.quran.com/api/v3/chapters/46/verses` I get all the verses, but when the application does it via `getChapterVerses` the reponse only contains 10 verses.

I'm curios how is this achieved. 

Thank you, great work again. I hope I can contribute 😀

**Comment by naveed-ahmad** [comment]
Verses endpoint will return only 10 verses each request, you can get the next set of verses using pagination. Please see the docs. 

https://quran.api-docs.io/v3/verses/list-verses
