### ISSUE TITLE
create donations page

### ISSUE THREAD

**Issue by mmahalwy** [quran/quran.com-frontend-next#7]
design here: http://beta.quran.com/pages/donations

**Comment by compako10** [comment]
I noticed that when I set up the dev environment the app is using a light theme. Is this new page supposed to be light theme as well with this design or is the task to make the page look exactly like that link.

Also does #11 and #9 have to be done before this one?

**Comment by mmahalwy** [comment]
@compako10 beta.quran.com will detect what mode you have on your OS. I have dark mode. But default is light theme. Please use light theme. 

As for #11 and #9. They are not needed to be done before

**Comment by mistat44** [comment]
Salam, I can pick this up

**Comment by ibraheemdev** [comment]
I am looking to get involved in this project. I can create this page. I am just looking for some general guidance, do I just have to convert the design from the beta page into a jsx component in the `src/pages_` directory?

**Comment by tifa2UP** [comment]
Ditto. blocked on the design. Will close the issue until we have the design specs. 

@ibraheemdev v3 could be found here: https://github.com/quran/quran.com-frontend-v2
