### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by Ademking** [quran/quran.com-frontend-next#733]
Discord icon

![image](https://user-images.githubusercontent.com/12462188/141148629-cdd0c7ac-b177-4a4f-a2e8-030dc86f61a1.png)

Select width is very small

![image](https://user-images.githubusercontent.com/12462188/141148746-6d147962-1fce-4df6-ace5-bd873414813f.png)

**Comment by muhajirdev** [comment]
The width issue still exist, will be fixed.
