### ISSUE TITLE
Saving last position and settings.

### ISSUE THREAD

**Issue by selim** [quran/quran.com-frontend-next#754]
Must be save last reading position and settings (Display setFont-size etc). May be use Cookie or Sign-in User.

**Comment by iyunusov** [comment]
Maybe would be better to use`localStorage`?

**Comment by selim** [comment]
If we setup a basic user/password, we can save user preferences and last reading position on server, and able to sync to all devices.

**Comment by osamasayed** [comment]
Alsalamu Alikum @selim we have already implemented authentication and do save the user preferences, bookmarks and last reading position. It's currently in beta and will be rolled out to all users very soon inshAllah.
