### ISSUE TITLE
Toast component should have "Error" and "Success" variant

### ISSUE THREAD

**Issue by muhajirdev** [quran/quran.com-frontend-next#797]
Currently our toast component only have 1 color. Just plain white.

![image](https://user-images.githubusercontent.com/12745166/142732008-7c234f09-52e2-49df-8843-dc6157096a7e.png)

We need to have "success" and "error" variant
- error variant should have "red" background color `var(--color-error-medium)`
- success variant should have "blue" background color. use `var(--color-success-medium)`

**Comment by talal-najam** [comment]
Salaam, was browsing through repo, looking for issues to contribute. Is this still needed? Seems like toast status have already been added in #810. JazakAllah

**Comment by osamasayed** [comment]
> Salaam, was browsing through repo, looking for issues to contribute. Is this still needed? Seems like toast status have already been added in #810. JazakAllah

Wa'likum Alsalam, Jazak Allah Kahiran for wanting to contribute, indeed toast statuses have already been added.
