### ISSUE TITLE
localize number, for example hijri prayer time

### ISSUE THREAD

**Issue by muhajirdev** [quran/quran.com-frontend-next#831]
![image](https://user-images.githubusercontent.com/12745166/143592930-5f960316-ac35-4dde-80fe-01a999faf273.png)

using the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString method

**Comment by MahranElmasri** [comment]
Hey @muhajirdev  @tifa2UP, I would like to start with this issue.
