### ISSUE TITLE
Make al Kahf pop to top of popular surahs on Friday

### ISSUE THREAD

**Issue by HackintoshwithUbuntu** [quran/quran.com-frontend-next#842]
Surah Kahf used to pop to first place on the "popular surahs" section, this was a feature that was previously supported (in some long ago frontend version) and I found this to be an extremely useful feature as many people obviously go to Surah Kahf on Fridays and this makes it easier to access. I'm assuming this could be done simply by checking the day of week on the client pc and bringing al kahf to the top if such day is Friday.

**Comment by osamasayed** [comment]
Alsalamu Alikum, Jazak Allah Khairan for proposing this! We currently have this section on the homepage that includes Surah Al Kahf for easier access already.
<img width="857" alt="Screen Shot 2022-08-26 at 6 19 48 AM" src="https://user-images.githubusercontent.com/15169499/186785148-715b3cc5-b19f-4087-8b1b-7bfe65023337.png">
