### ISSUE TITLE
About us page should include Sallallahu Alayhi Wasallam after the name of our Beloved Prophet.

### ISSUE THREAD

**Issue by iyunusov** [quran/quran.com-frontend-next#848]
There's a type after the name of beloved Prophet Muhammad (sallallahu alayhi wa ahli wasallam).
<img width="712" alt="Screenshot 2021-11-30 at 21 49 43" src="https://user-images.githubusercontent.com/11756762/144101040-b02f2a19-2a01-4811-bad1-df24e1be37cb.png">

**Comment by faiqali1** [comment]
I believe it's as simple as adding the correct unicode.

I am a new to Web Development may I have a go?

Many Thanks,

**Comment by muhajirdev** [comment]
feel free to submit a PR if you found an issue you think you can fix @faiqali1
