### ISSUE TITLE
Advance copy options selecting previously selected Ayah number instead of new one

### ISSUE THREAD

**Issue by hellowahab** [quran/quran.com-frontend-next#861]
Steps to reproduce:-

1. Open the chrome app for Quran, 
2. Have arabic and one translation enabled (Urdu)
3. Try using Advance Copy option for a Ayah
4. It will work fine for the first time
5. Now select second Ayah and try using Advance Copy option
6. It will show previously selected Ayah instead of the one being selected
7. 
<img width="916" alt="image" src="https://user-images.githubusercontent.com/12432/144542124-032145b7-06af-4cf4-bcb5-000ab7a0aa8d.png">

<img width="875" alt="image" src="https://user-images.githubusercontent.com/12432/144542166-c6aa2c59-f9b7-45d7-bb85-a5be22b23a21.png">

**Comment by osamasayed** [comment]
Alsamau Alikum @hellowahab, it seems this issue is related to our old [repo](https://github.com/quran/quran.com-frontend-v2) and not the Next.js's one.
