### ISSUE TITLE
Tafsir doesn't show when only 1 is selected

### ISSUE THREAD

**Issue by osamasayed** [quran/quran.com-frontend-next#881]
<img width="1440" alt="Screen Shot 2021-12-09 at 08 52 35" src="https://user-images.githubusercontent.com/15169499/145319908-f5e15364-66bf-4744-ab62-6a95c86a0319.png">
<img width="1440" alt="Screen Shot 2021-12-09 at 08 52 41" src="https://user-images.githubusercontent.com/15169499/145319914-0b5d9a78-feae-46c1-8234-8d9859ac4136.png">

**Comment by hazem3500** [comment]
I believe this is already solved, should we close the issue? 👀
