### ISSUE TITLE
Skeleton for tafsir and translation settings

### ISSUE THREAD

**Issue by muhajirdev** [quran/quran.com-frontend-next#895]
![image](https://user-images.githubusercontent.com/12745166/145534295-5eec907f-2b4b-436c-9c14-68a27b50e546.png)

Since skeleton is now transparent, it looks like this. notice the text `169` and `168`

We need a update the skeleton implementation for these settings.

**Comment by sksiyer** [comment]
Please include steps on how to recreate. JazakAllah

**Comment by osamasayed** [comment]
Related to #1770
