### ISSUE TITLE
Checkbox DLS does not looks great yet on dark theme

### ISSUE THREAD

**Issue by muhajirdev** [quran/quran.com-frontend-next#932]
![image](https://user-images.githubusercontent.com/12745166/146149466-6e3f9f17-c298-4eab-b7d2-3bcdf411668f.png)

We probably want to customize it. Perhaps something like this
![image](https://user-images.githubusercontent.com/12745166/146149439-bc8ee63d-e6f8-43eb-977b-0d2b0a1270e3.png)

**Comment by aathikahamed** [comment]
This might help: https://codepen.io/finnhvman/pen/zpygBB

**Comment by muhajirdev** [comment]
thanks @aathikahamed
