### ISSUE TITLE
Audio starats to play from random part and start random position on page

### ISSUE THREAD

**Issue by Mirodil** [quran/quran.com-frontend-next#97]
Hi,

When playing audio in sequence most of time it jumps into middle of end of audio in Safari/Firefox on mac.

Replication:
- open website in Safari(ipad) or Safari/Firefox(mac)
- navigate any chapter
- click/tap on play button in the first verse of a chapter
- and you can see the issue

**Comment by tifa2UP** [comment]
Salaam @Mirodil. Looks like this issue is related to v3 or v2 of quran.com. I'm gonna close this issue but feel free to re-open it in the correct repo
